# modify the prompt to contain git branch name if applicable
git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null)
  if [[ -n $ref ]]; then
    echo " %{$fg_bold[green]%}${ref#refs/heads/}%{$reset_color%}"
  fi
}
setopt promptsubst
export PS1='${SSH_CONNECTION+"%{$fg_bold[green]%}%n@%m:"}%{$fg_bold[blue]%}%c%{$reset_color%}$(git_prompt_info) %# '

# load our own completion functions
fpath=(~/.zsh/completion $fpath)

# completion
autoload -U compinit
compinit

# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done

# makes color constants available
autoload -U colors
colors

# enable colored output from ls, etc
export CLICOLOR=1

# history settings
setopt hist_ignore_all_dups inc_append_history
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

# awesome cd movements from zshkit
setopt autocd autopushd pushdminus pushdsilent pushdtohome cdablevars
DIRSTACKSIZE=5

# Enable extended globbing
setopt extendedglob

# Allow [ or ] whereever you want
unsetopt nomatch

# vi mode
bindkey -v
bindkey "^F" vi-cmd-mode
bindkey jj vi-cmd-mode

# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word
bindkey -s "^T" "^[Isudo ^[A" # "t" for "toughguy"

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# extra files in ~/.zsh/configs/pre , ~/.zsh/configs , and ~/.zsh/configs/post
# these are loaded first, second, and third, respectively.
_load_settings() {
  _dir="$1"
  if [ -d "$_dir" ]; then
    if [ -d "$_dir/pre" ]; then
      for config in "$_dir"/pre/**/*(N-.); do
        . $config
      done
    fi

    for config in "$_dir"/**/*(N-.); do
      case "$config" in
        "$_dir"/pre/*)
          :
          ;;
        "$_dir"/post/*)
          :
          ;;
        *)
          if [ -f $config ]; then
            . $config
          fi
          ;;
      esac
    done

    if [ -d "$_dir/post" ]; then
      for config in "$_dir"/post/**/*(N-.); do
        . $config
      done
    fi
  fi
}
_load_settings "$HOME/.zsh/configs"


#-------------
# zsh options
setopt no_beep correct complete_in_word correct rm_star_wait

#--------
# history

export HISTFILE=~/.zsh_history
export SAVEHIST=10000
export HISTSIZE=12000

setopt append_history           # use history for multiple zsh instances
setopt extended_history         # puts timestamps in the history
setopt hist_allow_clobber
setopt hist_reduce_blanks       # remov unneeded blanks
setopt inc_append_history
setopt share_history
setopt hist_no_store            # commands like history or fc are no longer stored
setopt hist_ignore_all_dups     # no duplicated entries like ls,cd,pwd etc.
setopt hist_ignore_space        # do not save commands with leading space in history


setopt hist_ignore_space      # Do not remember commands starting with space
setopt share_history          # Share history among sessions
setopt hist_verify            # Reload full command when runing from history
setopt hist_expire_dups_first # Remove dups when max size reached
setopt list_types             # Show ls -F style marks in file completion
setopt long_list_jobs         # Show pid in bg job list
setopt numeric_glob_sort      # When globbing numbered files, use real counting
setopt no_hist_beep           # Don not beep on history expansion errors
setopt hist_reduce_blanks     # Reduce whitespace in history
setopt interactive_comments   # Comments in history
setopt inc_append_history     # Append to history once executed
setopt prompt_subst           # Prompt more dynamic, allow function in prompt


#bindkey '^r' history-incremental-search-backward
#bindkey '^?' history-incremental-search-backward
bindkey "^[[5~" up-line-or-history
bindkey "^[[6~" down-line-or-history
bindkey "^[[H" beginning-of-line
bindkey "^[[1~" beginning-of-line
bindkey "^[[F"  end-of-line
bindkey "^[[4~" end-of-line
bindkey ' ' magic-space    # also do history expansion on space
bindkey '^I' complete-word # complete on tab, leave expansion to _expand


#history only on first substring of command you're typing
#bindkey "\e[A" up-line-or-search
#bindkey "\e[B" down-line-or-search
bindkey "\e[A" history-beginning-search-backward
bindkey "\e[B" history-beginning-search-forward
#new iterm binds up arrow to this, wtf, ^[[A is standard on all other xterm's
bindkey "\eOA" history-beginning-search-backward
bindkey "\eOB" history-beginning-search-forward

autoload up-line-or-beginning-search \
down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '\e[A' up-line-or-beginning-search
bindkey '\e[B' down-line-or-beginning-search



# Report to me when other people login/logout
watch=(notme)

# shell
export SHELL=`which zsh`

# Timezone
export TZ='Europe/Berlin'

alias l="ls -la"
alias v="mvim"

alias gitignore="curl -O https://gist.githubusercontent.com/jkuetemeier/98900a7ea5e9e419687e/raw/1560c82e611fa2c2fbea59882f8292ecad9a3551/.gitignore"

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
