#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "$JKSYSDIR/init.zsh" ]]; then
  source "$JKSYSDIR/init.zsh"
fi

# Customize to your needs...
